version: '3'

services:
  mysql_db:
    image: mysql:8.0.31
    container_name: mysql_db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=test
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
volumes:
  dbdata:

networks:
  app-network:
    driver: bridge